# Generated by Django 4.1.7 on 2023-05-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=400)),
                ('song1', models.CharField(max_length=20)),
                ('song2', models.CharField(max_length=20)),
                ('song3', models.CharField(max_length=20)),
            ],
        ),
    ]
