# Generated by Django 4.1.7 on 2023-05-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='created_at',
        ),
    ]
