# Generated by Django 4.1.7 on 2023-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='song1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='singer',
            name='song2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='singer',
            name='song3',
            field=models.CharField(max_length=50),
        ),
    ]
